using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

public class Projectile : MonoBehaviour
{
    Rigidbody2D rigidbody2d;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    void Awake()
    {
        rigidbody2d = GetComponent<Rigidbody2D>();  
    }
    void Update()
    {
        if (transform.position.magnitude > 100.0f)
        {
            Destroy(gameObject);
        }
    }
    // Update is called once per frame
    public void Launch(Vector2 direction, float force)
    {
        Vector2 finalForce = direction.normalized * force;
        finalForce += Vector2.up * (force * 0.5f);
       
        rigidbody2d.AddForce(finalForce, ForceMode2D.Impulse);
    }

    void OnTriggerEnter2D(Collider2D other)
    {
        EnemyController enemy = other.GetComponent<EnemyController>();
        if (enemy != null)
        {
            enemy.Fix();
        }
        Destroy(gameObject);
    }

    void OnCollisionEnter2D(Collision2D other)
    {
        Destroy(gameObject);
    }
}
